# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: flpop <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2014/09/16 21:32:12 by flpop             #+#    #+#              #
#    Updated: 2014/09/16 21:32:16 by flpop            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc -Wall -Wextra -Werror ft_atoi.c ft_putchar.c ft_putnbr.c ft_putstr.c ft_strlen.c main.c operators.c -o do-op

clean:
	rm -rf do-op
